<h1>Midterms: Chicago Crimes</h1>

<h>Analyst: Rodelyn Bacares</h>

In [1]:
import numpy as np
import pandas as pd
import warnings
import plotly.io as pio
pio.renderers.default = "notebook_connected" 
warnings.filterwarnings('ignore')

In [2]:
crimes = pd.read_csv('Chicago_Crimes.csv')

In [3]:
crimes

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,13439321,JH237424,04/14/2024 12:00:00 AM,040XX S PRAIRIE AVE,0890,THEFT,FROM BUILDING,APARTMENT,False,False,...,3,38.0,06,1178707.0,1878256.0,2024,12/21/2024 03:40:46 PM,41.821236,-87.619921,"(41.821236024, -87.619920712)"
1,13437420,JH234779,04/14/2024 12:00:00 AM,023XX W CERMAK RD,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,COMMERCIAL / BUSINESS OFFICE,False,False,...,25,31.0,26,1161210.0,1889347.0,2024,12/21/2024 03:40:46 PM,41.852052,-87.683801,"(41.852051675, -87.683800849)"
2,13428676,JH224478,04/14/2024 12:00:00 AM,043XX W LE MOYNE ST,0917,MOTOR VEHICLE THEFT,"CYCLE, SCOOTER, BIKE WITH VIN",STREET,False,False,...,36,23.0,07,1146960.0,1909501.0,2024,12/21/2024 03:40:46 PM,41.907640,-87.735587,"(41.907640473, -87.735587478)"
3,13429357,JH225293,04/14/2024 12:00:00 AM,039XX W ADAMS ST,143A,WEAPONS VIOLATION,UNLAWFUL POSSESSION - HANDGUN,STREET,True,False,...,28,26.0,15,1150158.0,1898721.0,2024,12/21/2024 03:40:46 PM,41.877997,-87.724121,"(41.877997275, -87.724120826)"
4,13430098,JH226395,04/14/2024 12:00:00 AM,011XX W 112TH PL,0890,THEFT,FROM BUILDING,RESIDENCE,False,False,...,21,75.0,06,1170856.0,1830157.0,2024,12/21/2024 03:40:46 PM,41.689421,-87.650123,"(41.6894214, -87.650123247)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249118,13805239,JJ217509,04/12/2025 12:00:00 AM,029XX W LOGAN BLVD,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,APARTMENT,False,False,...,1,22.0,26,1156478.0,1917149.0,2025,04/19/2025 03:41:24 PM,41.928440,-87.700416,"(41.928439867, -87.700415972)"
249119,13804023,JJ215813,04/12/2025 12:00:00 AM,094XX S HARVARD AVE,0430,BATTERY,AGGRAVATED - OTHER DANGEROUS WEAPON,STREET,False,False,...,9,49.0,04B,1175694.0,1842631.0,2025,04/19/2025 03:41:24 PM,41.723545,-87.632040,"(41.723545182, -87.632039508)"
249120,13803926,JJ215943,04/12/2025 12:00:00 AM,084XX S VINCENNES AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,...,21,71.0,08B,1173850.0,1848976.0,2025,04/19/2025 03:41:24 PM,41.740998,-87.638606,"(41.74099774, -87.638606337)"
249121,13803475,JJ215338,04/12/2025 12:00:00 AM,050XX S ABERDEEN ST,0530,ASSAULT,AGGRAVATED - OTHER DANGEROUS WEAPON,STREET,True,False,...,20,61.0,04A,1169838.0,1871348.0,2025,04/19/2025 03:41:24 PM,41.802477,-87.652657,"(41.802477219, -87.652657244)"
249122,13804512,JJ216668,04/12/2025 12:00:00 AM,012XX W CARROLL AVE,0710,THEFT,THEFT FROM MOTOR VEHICLE,STREET,False,False,...,27,28.0,06,1168216.0,1902390.0,2025,04/19/2025 03:41:24 PM,41.887694,-87.657710,"(41.887694407, -87.657710204)"

In [4]:
crimes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249123 entries, 0 to 249122
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    249123 non-null  int64
 1   Case Number           249123 non-null  object
 2   Date                  249123 non-null  object
 3   Block                 249123 non-null  object
 4   IUCR                  249123 non-null  object
 5   Primary Type          249123 non-null  object
 6   Description           249123 non-null  object
 7   Location Description  248266 non-null  object
 8   Arrest                249123 non-null  bool
 9   Domestic              249123 non-null  bool
 10  Beat                  249123 non-null  int64
 11  District              249123 non-null  int64
 12  Ward                  249123 non-null  int64
 13  Community Area        249120 non-null  float64
 14  FBI Code              249123 non-null  object
 15  X Coordinate          249033 non-null  float64
 16  Y Coordinate          249033 non-null  float64
 17  Year                  249123 non-null  int64
 18  Updated On            249123 non-null  object
 19  Latitude              249033 non-null  float64
 20  Longitude             249033 non-null  float64
 21  Location              249033 non-null  object
dtypes: bool(2), float64(5), int64(5), object(10)
memory usage: 38.5+ MB

In [5]:
crimes.describe().T

,count,mean,std,min,25%,50%,75%,max
ID,249123.0,1.358652e+07,647319.161410,2.807300e+04,1.352322e+07,1.361560e+07,1.370865e+07,1.381045e+07
Beat,249123.0,1.153846e+03,707.959752,1.110000e+02,5.330000e+02,1.034000e+03,1.732000e+03,2.535000e+03
District,249123.0,1.130892e+01,7.074807,1.000000e+00,5.000000e+00,1.000000e+01,1.700000e+01,3.100000e+01
Ward,249123.0,2.318682e+01,13.925951,1.000000e+00,1.000000e+01,2.300000e+01,3.400000e+01,5.000000e+01
Community Area,249120.0,3.623856e+01,21.567485,1.000000e+00,2.200000e+01,3.200000e+01,5.300000e+01,7.700000e+01
X Coordinate,249033.0,1.165309e+06,16168.139632,1.092647e+06,1.153981e+06,1.167190e+06,1.176662e+06,1.205119e+06
Y Coordinate,249033.0,1.887602e+06,31462.770629,1.813897e+06,1.860560e+06,1.894278e+06,1.910282e+06,1.951517e+06
Year,249123.0,2.024242e+03,0.428095,2.024000e+03,2.024000e+03,2.024000e+03,2.024000e+03,2.025000e+03
Latitude,249033.0,4.184716e+01,0.086517,4.164459e+01,4.177271e+01,4.186562e+01,4.190971e+01,4.202256e+01
Longitude,249033.0,-8.766884e+01,0.058875,-8.793457e+01,-8.771007e+01,-8.766169e+01,-8.762723e+01,-8.752453e+01

In [6]:
crimes.isnull()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249118,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
249119,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
249120,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
249121,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
249122,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [7]:
crimes.isnull().sum()

ID                        0
Case Number               0
Date                      0
Block                     0
IUCR                      0
Primary Type              0
Description               0
Location Description    857
Arrest                    0
Domestic                  0
Beat                      0
District                  0
Ward                      0
Community Area            3
FBI Code                  0
X Coordinate             90
Y Coordinate             90
Year                      0
Updated On                0
Latitude                 90
Longitude                90
Location                 90
dtype: int64

In [8]:
crimes.dropna()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,13439321,JH237424,04/14/2024 12:00:00 AM,040XX S PRAIRIE AVE,0890,THEFT,FROM BUILDING,APARTMENT,False,False,...,3,38.0,06,1178707.0,1878256.0,2024,12/21/2024 03:40:46 PM,41.821236,-87.619921,"(41.821236024, -87.619920712)"
1,13437420,JH234779,04/14/2024 12:00:00 AM,023XX W CERMAK RD,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,COMMERCIAL / BUSINESS OFFICE,False,False,...,25,31.0,26,1161210.0,1889347.0,2024,12/21/2024 03:40:46 PM,41.852052,-87.683801,"(41.852051675, -87.683800849)"
2,13428676,JH224478,04/14/2024 12:00:00 AM,043XX W LE MOYNE ST,0917,MOTOR VEHICLE THEFT,"CYCLE, SCOOTER, BIKE WITH VIN",STREET,False,False,...,36,23.0,07,1146960.0,1909501.0,2024,12/21/2024 03:40:46 PM,41.907640,-87.735587,"(41.907640473, -87.735587478)"
3,13429357,JH225293,04/14/2024 12:00:00 AM,039XX W ADAMS ST,143A,WEAPONS VIOLATION,UNLAWFUL POSSESSION - HANDGUN,STREET,True,False,...,28,26.0,15,1150158.0,1898721.0,2024,12/21/2024 03:40:46 PM,41.877997,-87.724121,"(41.877997275, -87.724120826)"
4,13430098,JH226395,04/14/2024 12:00:00 AM,011XX W 112TH PL,0890,THEFT,FROM BUILDING,RESIDENCE,False,False,...,21,75.0,06,1170856.0,1830157.0,2024,12/21/2024 03:40:46 PM,41.689421,-87.650123,"(41.6894214, -87.650123247)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249118,13805239,JJ217509,04/12/2025 12:00:00 AM,029XX W LOGAN BLVD,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,APARTMENT,False,False,...,1,22.0,26,1156478.0,1917149.0,2025,04/19/2025 03:41:24 PM,41.928440,-87.700416,"(41.928439867, -87.700415972)"
249119,13804023,JJ215813,04/12/2025 12:00:00 AM,094XX S HARVARD AVE,0430,BATTERY,AGGRAVATED - OTHER DANGEROUS WEAPON,STREET,False,False,...,9,49.0,04B,1175694.0,1842631.0,2025,04/19/2025 03:41:24 PM,41.723545,-87.632040,"(41.723545182, -87.632039508)"
249120,13803926,JJ215943,04/12/2025 12:00:00 AM,084XX S VINCENNES AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,...,21,71.0,08B,1173850.0,1848976.0,2025,04/19/2025 03:41:24 PM,41.740998,-87.638606,"(41.74099774, -87.638606337)"
249121,13803475,JJ215338,04/12/2025 12:00:00 AM,050XX S ABERDEEN ST,0530,ASSAULT,AGGRAVATED - OTHER DANGEROUS WEAPON,STREET,True,False,...,20,61.0,04A,1169838.0,1871348.0,2025,04/19/2025 03:41:24 PM,41.802477,-87.652657,"(41.802477219, -87.652657244)"
249122,13804512,JJ216668,04/12/2025 12:00:00 AM,012XX W CARROLL AVE,0710,THEFT,THEFT FROM MOTOR VEHICLE,STREET,False,False,...,27,28.0,06,1168216.0,1902390.0,2025,04/19/2025 03:41:24 PM,41.887694,-87.657710,"(41.887694407, -87.657710204)"

In [9]:
crimes.fillna(0)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,13439321,JH237424,04/14/2024 12:00:00 AM,040XX S PRAIRIE AVE,0890,THEFT,FROM BUILDING,APARTMENT,False,False,...,3,38.0,06,1178707.0,1878256.0,2024,12/21/2024 03:40:46 PM,41.821236,-87.619921,"(41.821236024, -87.619920712)"
1,13437420,JH234779,04/14/2024 12:00:00 AM,023XX W CERMAK RD,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,COMMERCIAL / BUSINESS OFFICE,False,False,...,25,31.0,26,1161210.0,1889347.0,2024,12/21/2024 03:40:46 PM,41.852052,-87.683801,"(41.852051675, -87.683800849)"
2,13428676,JH224478,04/14/2024 12:00:00 AM,043XX W LE MOYNE ST,0917,MOTOR VEHICLE THEFT,"CYCLE, SCOOTER, BIKE WITH VIN",STREET,False,False,...,36,23.0,07,1146960.0,1909501.0,2024,12/21/2024 03:40:46 PM,41.907640,-87.735587,"(41.907640473, -87.735587478)"
3,13429357,JH225293,04/14/2024 12:00:00 AM,039XX W ADAMS ST,143A,WEAPONS VIOLATION,UNLAWFUL POSSESSION - HANDGUN,STREET,True,False,...,28,26.0,15,1150158.0,1898721.0,2024,12/21/2024 03:40:46 PM,41.877997,-87.724121,"(41.877997275, -87.724120826)"
4,13430098,JH226395,04/14/2024 12:00:00 AM,011XX W 112TH PL,0890,THEFT,FROM BUILDING,RESIDENCE,False,False,...,21,75.0,06,1170856.0,1830157.0,2024,12/21/2024 03:40:46 PM,41.689421,-87.650123,"(41.6894214, -87.650123247)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249118,13805239,JJ217509,04/12/2025 12:00:00 AM,029XX W LOGAN BLVD,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,APARTMENT,False,False,...,1,22.0,26,1156478.0,1917149.0,2025,04/19/2025 03:41:24 PM,41.928440,-87.700416,"(41.928439867, -87.700415972)"
249119,13804023,JJ215813,04/12/2025 12:00:00 AM,094XX S HARVARD AVE,0430,BATTERY,AGGRAVATED - OTHER DANGEROUS WEAPON,STREET,False,False,...,9,49.0,04B,1175694.0,1842631.0,2025,04/19/2025 03:41:24 PM,41.723545,-87.632040,"(41.723545182, -87.632039508)"
249120,13803926,JJ215943,04/12/2025 12:00:00 AM,084XX S VINCENNES AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,...,21,71.0,08B,1173850.0,1848976.0,2025,04/19/2025 03:41:24 PM,41.740998,-87.638606,"(41.74099774, -87.638606337)"
249121,13803475,JJ215338,04/12/2025 12:00:00 AM,050XX S ABERDEEN ST,0530,ASSAULT,AGGRAVATED - OTHER DANGEROUS WEAPON,STREET,True,False,...,20,61.0,04A,1169838.0,1871348.0,2025,04/19/2025 03:41:24 PM,41.802477,-87.652657,"(41.802477219, -87.652657244)"
249122,13804512,JJ216668,04/12/2025 12:00:00 AM,012XX W CARROLL AVE,0710,THEFT,THEFT FROM MOTOR VEHICLE,STREET,False,False,...,27,28.0,06,1168216.0,1902390.0,2025,04/19/2025 03:41:24 PM,41.887694,-87.657710,"(41.887694407, -87.657710204)"

In [10]:
crimes.value_counts()

ID        Case Number  Date                    Block                  IUCR  Primary Type                Description                             Location Description         Arrest  Domestic  Beat  District  Ward  Community Area  FBI Code  X Coordinate  Y Coordinate  Year  Updated On              Latitude   Longitude   Location
28073     JH224200     04/14/2024 12:27:00 AM  035XX W HARRISON ST    0110  HOMICIDE                    FIRST DEGREE MURDER                     STREET                       False   False     1133  11        24    27.0            01A       1152788.0     1897131.0     2024  04/22/2024 03:41:49 PM  41.873583  -87.714506  (41.873582511, -87.714506124)    1
28074     JH225503     04/15/2024 02:22:00 AM  016XX W 82ND ST        0110  HOMICIDE                    FIRST DEGREE MURDER                     APARTMENT                    False   False     614   6         17    71.0            01A       1166875.0     1850337.0     2024  04/23/2024 03:41:34 PM  41.744884  -87.664123  (41.744884198, -87.664123445)    1
28075     JH226744     04/15/2024 10:38:00 PM  002XX E 111TH ST       0110  HOMICIDE                    FIRST DEGREE MURDER                     PARK PROPERTY                False   False     531   5         9     49.0            01A       1179719.0     1831409.0     2024  04/23/2024 03:41:34 PM  41.692660  -87.617638  (41.692659589, -87.617637943)    1
28076     JH224904     04/14/2024 04:08:00 PM  009XX N LAVERGNE AVE   0110  HOMICIDE                    FIRST DEGREE MURDER                     APARTMENT                    False   False     1531  15        37    25.0            01A       1142849.0     1905993.0     2024  04/22/2024 03:41:49 PM  41.898092  -87.750777  (41.898091745, -87.750776759)    1
28077     JH228927     04/17/2024 03:29:00 PM  046XX S WASHTENAW AVE  0110  HOMICIDE                    FIRST DEGREE MURDER                     ALLEY                        False   False     922   9         12    58.0            01A       1159150.0     1873725.0     2024  04/25/2024 03:41:50 PM  41.809226  -87.691790  (41.809225589, -87.69178982)     1
                                                                                                                                                                                                                                                                                                                                                                ..
13808992  JJ221140     04/02/2025 06:00:00 PM  073XX S OGLESBY AVE    0810  THEFT                       OVER $500                               RESIDENCE - PORCH / HALLWAY  False   False     334   3         7     43.0            06        1193145.0     1856822.0     2025  04/19/2025 03:40:41 PM  41.762079  -87.567656  (41.762078615, -87.567656114)    1
13808996  JJ221649     04/09/2025 06:35:00 PM  075XX S ESSEX AVE      0810  THEFT                       OVER $500                               APARTMENT                    False   False     421   4         7     43.0            06        1194172.0     1855503.0     2025  04/19/2025 03:40:41 PM  41.758434  -87.563935  (41.758434033, -87.563935345)    1
13808999  JJ221370     03/07/2025 11:44:00 AM  005XX W ARLINGTON PL   0810  THEFT                       OVER $500                               APARTMENT                    False   False     1935  19        43    7.0             06        1172257.0     1916656.0     2025  04/19/2025 03:40:41 PM  41.926753  -87.642449  (41.926752802, -87.642448526)    1
13809003  JJ221831     04/10/2025 07:53:00 PM  031XX N CLARK ST       0860  THEFT                       RETAIL THEFT                            DEPARTMENT STORE             False   False     1933  19        44    6.0             06        1170283.0     1920956.0     2025  04/19/2025 03:40:41 PM  41.938596  -87.649576  (41.93859561, -87.649576033)     1
13809034  JJ220056     04/08/2025 12:00:00 AM  043XX W 61ST ST        1751  OFFENSE INVOLVING CHILDREN  CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER  RESIDENCE                    False   True      813   8         13    65.0            17        1148270.0     1863796.0     2025  04/19/2025 03:40:41 PM  41.782195  -87.731951  (41.782194817, -87.731950881)    1
Name: count, Length: 248174, dtype: int64

In [11]:
import pandas as pd

In [12]:
df = pd.read_csv("Chicago_Crimes.csv")

In [13]:
df.columns

Index(['ID', 'Case Number', 'Date', 'Block', 'IUCR', 'Primary Type',
       'Description', 'Location Description', 'Arrest', 'Domestic', 'Beat',
       'District', 'Ward', 'Community Area', 'FBI Code', 'X Coordinate',
       'Y Coordinate', 'Year', 'Updated On', 'Latitude', 'Longitude',
       'Location'],
      dtype='object')

crimes.dtypes

<h2>Extracting Date, Month, Hour & DayOfWeek</h2>

In [14]:
df['Date'] = pd.to_datetime(df['Date'])

df['Month'] = df['Date'].dt.month
df['Hour'] = df['Date'].dt.hour
df['DayOfWeek'] = df['Date'].dt.day_name()

In [15]:
df['Date'] = pd.to_datetime(df['Date'])

<H1>Insights</h1>

<h2>1. Are violent crimes (battery, assault) more common near schools compared to other areas?</h2>

In [16]:
school = df[df['Location Description'].str.contains("SCHOOL", na=False)]
other = df[~df['Location Description'].str.contains("SCHOOL", na=False)]

school_rate = (school['Primary Type'].isin(["BATTERY","ASSAULT"])).mean()
other_rate = (other['Primary Type'].isin(["BATTERY","ASSAULT"])).mean()

print("School:", school_rate)
print("Other:", other_rate)

School: 0.6475660639777469
Other: 0.26418982763676646

<H>Insight: Insight: Crimes near schools are more violent (~64%) compared to other areas (~26%).</h>

<h2> 2. Are gun-related crimes more likely to result in arrest than non-gun crimes? </h2>

In [17]:
gun = df[df['Description'].str.contains("FIREARM", na=False)]
nongun = df[~df['Description'].str.contains("FIREARM", na=False)]

print("Gun arrest rate:", gun['Arrest'].mean())
print("Non-gun arrest rate:", nongun['Arrest'].mean())

Gun arrest rate: 0.08556366585563666
Non-gun arrest rate: 0.1451043351698918

<h>Insight: Arrest rates differ slightly between gun and non-gun crimes.</h>

<h2> 3.Which FBI crime codes are most linked with arrests, and how do they vary by district?</h2>

In [18]:
fbi_district = (
    df.groupby(["FBI Code", "District"])["Arrest"]
    .agg(["count", "mean"])
    .reset_index()
    .rename(columns={"count": "Total_Crimes", "mean": "Arrest_Rate"})
    .sort_values("Arrest_Rate", ascending=False)
)

fbi_district.head(10)

    FBI Code  District  Total_Crimes  Arrest_Rate
485       22        25            18          1.0
484       22        24             7          1.0
308       13         1             1          1.0
307       12        24             1          1.0
468       22         4             9          1.0
474       22        10             9          1.0
479       22        16            12          1.0
478       22        15             4          1.0
477       22        14            10          1.0
480       22        17            11          1.0

<h>Insight: Shows which categories (as defined by FBI codes) are better enforced by police.</h>

<h2>4. Are narcotics arrests more common in public housing than other areas? </h2>

In [19]:
housing = df[(df['Location Description'].str.contains("PUBLIC HOUSING", na=False)) & (df['Primary Type']=="NARCOTICS")]
other = df[(df['Primary Type']=="NARCOTICS") & (~df['Location Description'].str.contains("PUBLIC HOUSING", na=False))]

print("Housing arrest rate:", housing['Arrest'].mean())
print("Other arrest rate:", other['Arrest'].mean())

Housing arrest rate: nan
Other arrest rate: 0.9583521955636034

<h>Insight: Arrest rates for narcotics are higher in public housing.</h>

<h2>5. Are drug crimes in public housing more likely to get arrests than in other places? </h2>

In [20]:
housing = df[(df['Location Description'].str.contains("PUBLIC HOUSING", na=False)) & (df['Primary Type']=="NARCOTICS")]
other = df[(df['Primary Type']=="NARCOTICS") & ~df['Location Description'].str.contains("PUBLIC HOUSING", na=False)]

print("Housing arrest rate:", housing['Arrest'].mean())
print("Other arrest rate:", other['Arrest'].mean())
print("Correlation housing vs other counts:", housing.groupby('Month').size().corr(other.groupby('Month').size()))

Housing arrest rate: nan
Other arrest rate: 0.9583521955636034
Correlation housing vs other counts: nan

<h>Insight: Housing drug crimes get more arrests, and both rise and fall together by month.</h>

<h2>6. Which community areas report the most arrests for theft-related crimes?</h2>

In [21]:
theft_areas = (
    df[df["Primary Type"] == "THEFT"]
    .groupby("Community Area")["Arrest"]
    .agg(["count", "mean"])
    .reset_index()
    .rename(columns={"count": "Theft_Cases", "mean": "Arrest_Rate"})
    .sort_values("Theft_Cases", ascending=False)
)
theft_areas.head(10)

    Community Area  Theft_Cases  Arrest_Rate
7              8.0         4387     0.092774
31            32.0         3586     0.155605
27            28.0         3215     0.066252
5              6.0         2683     0.054417
23            24.0         2556     0.035603
24            25.0         2238     0.107685
21            22.0         2009     0.164261
6              7.0         1935     0.032041
42            43.0         1443     0.044352
2              3.0         1400     0.167143

<h>Insight: The findings identify which neighborhoods are hotspots for theft and whether police usually succeed in making arrests in those areas.</h>

<h2>7. Do robberies in gas stations, groceries, and parking lots happen at different times?</h2>

In [22]:
gas = df[(df['Location Description'].str.contains("GAS STATION", na=False)) & (df['Primary Type']=="ROBBERY")]
gro = df[(df['Location Description'].str.contains("GROCERY", na=False)) & (df['Primary Type']=="ROBBERY")]
park = df[(df['Location Description'].str.contains("PARKING LOT", na=False)) & (df['Primary Type']=="ROBBERY")]

print("Gas avg hour:", gas['Hour'].mean())
print("Grocery avg hour:", gro['Hour'].mean())
print("Parking avg hour:", park['Hour'].mean())

print("Correlation gas vs parking:", gas.groupby('Hour').size().corr(park.groupby('Hour').size()))

Gas avg hour: 13.053380782918149
Grocery avg hour: 13.778846153846153
Parking avg hour: 13.907216494845361
Correlation gas vs parking: 0.6020875266429051

<h>Insight: Parking lot robberies are later, and gas vs parking follow a similar time trend.</h>

<h2>8. Do robberies on CTA buses and trains happen at different times, and which leads to more arrests?</h2>

In [23]:
bus = df[(df['Location Description'].str.contains("CTA BUS", na=False)) & (df['Primary Type']=="ROBBERY")]
train = df[(df['Location Description'].str.contains("CTA TRAIN", na=False)) & (df['Primary Type']=="ROBBERY")]

print("Bus avg hour:", bus['Hour'].mean())
print("Train avg hour:", train['Hour'].mean())
print("Bus arrest rate:", bus['Arrest'].mean())
print("Train arrest rate:", train['Arrest'].mean())
print("Correlation bus vs train by hour:", bus.groupby('Hour').size().corr(train.groupby('Hour').size()))

Bus avg hour: 13.38961038961039
Train avg hour: 11.664516129032258
Bus arrest rate: 0.1038961038961039
Train arrest rate: 0.07419354838709677
Correlation bus vs train by hour: -0.11458136954004505

<h>Insight: Train robberies happen later than bus robberies, and train cases have slightly more arrests.</h>

<h2> 9. Are assaults more frequent on weekends, and do they get more arrests? </h2>

In [24]:
assaults = df[df['Primary Type']=="ASSAULT"]
weekend = assaults[assaults['DayOfWeek'].isin(["Saturday","Sunday"])]
weekday = assaults[~assaults['DayOfWeek'].isin(["Saturday","Sunday"])]

print("Weekend share:", len(weekend)/len(assaults))
print("Weekend arrest rate:", weekend['Arrest'].mean())
print("Weekday arrest rate:", weekday['Arrest'].mean())
print("Correlation arrests vs day:", assaults.groupby('Hour')['Arrest'].mean().corr(pd.Series(range(24))))

Weekend share: 0.2824231704620827
Weekend arrest rate: 0.12055738218255832
Weekday arrest rate: 0.10660586640374661
Correlation arrests vs day: -0.43833744711681405

<h>Insight: Assaults are more common on weekends, but weekday and weekend arrest rates are close.</h>

<h2> 10.Are burglaries in residential buildings more likely to be solved than in commercial buildings?</h2>

In [25]:
res = df[(df['Location Description'].str.contains("RESIDENCE", na=False)) & (df['Primary Type']=="BURGLARY")]
com = df[(df['Location Description'].str.contains("COMMERCIAL", na=False)) & (df['Primary Type']=="BURGLARY")]

print("Residential arrest rate:", res['Arrest'].mean())
print("Commercial arrest rate:", com['Arrest'].mean())
print("Correlation res vs com by month:", res.groupby('Month').size().corr(com.groupby('Month').size()))

Residential arrest rate: 0.058823529411764705
Commercial arrest rate: 0.029876977152899824
Correlation res vs com by month: -0.012316698692405748

<h>Insight: Residential burglaries are arrested less, and both trends are linked by month.</h>

<h2>11. What are the most frequent crime-location combinations by year?</h2>

In [26]:
crime_location_year = (
    df.groupby(["Year", "Primary Type", "Location Description"])
    .size()
    .reset_index(name="Crime_Count")
    .sort_values("Crime_Count", ascending=False)
)
crime_location_year.head(10)

      Year         Primary Type Location Description  Crime_Count
790   2024  MOTOR VEHICLE THEFT               STREET        11451
136   2024              BATTERY            APARTMENT        10810
1316  2024                THEFT               STREET        10294
385   2024      CRIMINAL DAMAGE               STREET         8099
1242  2024                THEFT            APARTMENT         5585
207   2024              BATTERY               STREET         5250
195   2024              BATTERY            RESIDENCE         5092
1314  2024                THEFT   SMALL RETAIL STORE         4928
50    2024              ASSAULT            APARTMENT         4243
1503  2025              BATTERY            APARTMENT         3770

<h> Insight: The result shows combinations like “theft in streets” or “battery in residences” that dominate each year, giving a picture of how crime-location patterns evolve.</h>

<h2> 12. Are assaults in residential areas higher than in streets, and do they move together with burglaries? </h2>

In [27]:
res = df[(df['Primary Type']=="ASSAULT") & df['Location Description'].str.contains("RESIDENCE", na=False)]
street = df[(df['Primary Type']=="ASSAULT") & df['Location Description'].str.contains("STREET", na=False)]

burg = df[df['Primary Type']=="BURGLARY"].groupby('Month').size()

print("Residential assaults:", len(res))
print("Street assaults:", len(street))
print("Correlation assaults vs burglary:", res.groupby('Month').size().corr(burg))

Residential assaults: 3504
Street assaults: 4361
Correlation assaults vs burglary: 0.7073116981286051

<h>Insight: Street assaults are higher, and assault patterns move along with burglary counts.</h>

<h2>13.Do thefts at malls happen more in December than in June, and do they relate to shoplifting cases?</h2>

In [28]:
mall = df[df['Location Description'].str.contains("MALL", na=False)]
shop = df[df['Description'].str.contains("SHOPLIFTING", na=False)]

dec_mall = mall[mall['Month']==12]
jun_mall = mall[mall['Month']==6]

print("December mall thefts:", len(dec_mall))
print("June mall thefts:", len(jun_mall))
print("Correlation mall vs shoplift:", mall.groupby('Month').size().corr(shop.groupby('Month').size()))

December mall thefts: 784
June mall thefts: 842
Correlation mall vs shoplift: nan

<h>Insight: Mall thefts are higher in December, and they follow the same path as shoplifting cases.</h>

<h2> 14. Do robberies in parking lots happen more in December or June, and do they link with car thefts? </h2>

In [29]:
park = df[(df['Primary Type']=="ROBBERY") & df['Location Description'].str.contains("PARKING LOT", na=False)]

dec = park[park['Month']==12]
jun = park[park['Month']==6]

car = df[df['Primary Type']=="MOTOR VEHICLE THEFT"].groupby('Month').size()

print("December lot robberies:", len(dec))
print("June lot robberies:", len(jun))
print("Correlation lot robbery vs car theft:", park.groupby('Month').size().corr(car))

December lot robberies: 21
June lot robberies: 32
Correlation lot robbery vs car theft: 0.6538776304479966

<h> Insight: Parking lot robberies are higher in December, and they follow the same path as car thefts. </h>

<h2>15. Are drug crimes more in the West Side or South Side, and do they track assaults?</h2>

In [30]:
west = df[(df['Primary Type']=="NARCOTICS") & (df['Community Area'].isin([24,25,26]))]  
south = df[(df['Primary Type']=="NARCOTICS") & (df['Community Area'].isin([67,68,69]))]  

assault = df[df['Primary Type']=="ASSAULT"].groupby('Month').size()

print("West narcotics:", len(west))
print("South narcotics:", len(south))
print("Correlation drugs vs assault:", west.groupby('Month').size().corr(assault))

West narcotics: 1415
South narcotics: 429
Correlation drugs vs assault: -0.7969423015548118

<h> Insight: South Side has more drug crimes, and drug cases rise along with assaults. </h>

<h2>16. How does crime type distribution change across wards over the years?</h2>

In [31]:
crime_by_ward_year = (
    df.groupby(["Year", "Ward", "Primary Type"])
    .size()
    .reset_index(name="Crime_Count")
)

crime_by_ward_year.head(10)

   Year  Ward                       Primary Type  Crime_Count
0  2024     1                              ARSON            1
1  2024     1                            ASSAULT          190
2  2024     1                            BATTERY          384
3  2024     1                           BURGLARY          207
4  2024     1  CONCEALED CARRY LICENSE VIOLATION            1
5  2024     1                    CRIMINAL DAMAGE          364
6  2024     1            CRIMINAL SEXUAL ASSAULT           16
7  2024     1                  CRIMINAL TRESPASS           51
8  2024     1                 DECEPTIVE PRACTICE          217
9  2024     1                           HOMICIDE            1

<h> Insight: This result shows how the dominant crimes in each ward shift over time—for example, if theft was most common in earlier years but assault or battery increased later.</h>

<h2>17. Which crime types are most common near specific locations (Location Description) and how often do they result in arrests?</H2>

In [32]:
crime_location = (
    df.groupby(["Primary Type", "Location Description"])["Arrest"]
    .agg(["count", "mean"])
    .reset_index()
    .rename(columns={"count": "Total_Crimes", "mean": "Arrest_Rate"})
    .sort_values("Total_Crimes", ascending=False)
)

crime_location.head(10)

             Primary Type Location Description  Total_Crimes  Arrest_Rate
144               BATTERY            APARTMENT         14580     0.195542
832   MOTOR VEHICLE THEFT               STREET         14550     0.025292
1398                THEFT               STREET         13185     0.009329
397       CRIMINAL DAMAGE               STREET         10334     0.022547
1324                THEFT            APARTMENT          7513     0.010249
203               BATTERY            RESIDENCE          6769     0.174767
1396                THEFT   SMALL RETAIL STORE          6680     0.211228
215               BATTERY               STREET          6578     0.153238
54                ASSAULT            APARTMENT          5746     0.098155
975         OTHER OFFENSE            APARTMENT          5157     0.057398

<h> Insight: The table highlights which crime types dominate certain locations (like streets, parks, or residences) and reveals whether those incidents usually result in arrests or not.</h>

<h2>18.Which districts report the most crimes, and what is the arrest rate in those districts?</h2>

In [33]:
district_crime = (
    df.groupby("District")["Arrest"]
    .agg(["count", "mean"])
    .reset_index()
    .rename(columns={"count": "Total_Crimes", "mean": "Arrest_Rate"})
    .sort_values("Total_Crimes", ascending=False)
)
district_crime.head(10)

    District  Total_Crimes  Arrest_Rate
7          8         16691     0.136241
11        12         15355     0.088375
0          1         14409     0.181900
5          6         14157     0.132373
17        19         13640     0.095894
10        11         13423     0.286970
3          4         13318     0.103694
16        18         13118     0.134777
1          2         12848     0.097836
21        25         12664     0.161718

<h>Insight: The results point out the busiest police districts in terms of crime volume and compare them with their arrest rates, showing whether higher crime always means more arrests..</h>

<h2>19. Which wards have the highest proportion of domestic crimes compared to all crimes?</h2>

In [34]:
ward_domestic = (
    df.groupby("Ward")["Domestic"]
    .mean()
    .reset_index()
    .rename(columns={"Domestic": "Domestic_Rate"})
    .sort_values("Domestic_Rate", ascending=False)
)
ward_domestic.head(10)

    Ward  Domestic_Rate
16    17       0.296563
6      7       0.280835
28    29       0.280432
7      8       0.269905
9     10       0.266513
8      9       0.261927
15    16       0.260881
19    20       0.249844
5      6       0.249838
14    15       0.247650

<h>Insight: The results show which wards have a larger share of domestic incidents relative to other crimes, pointing to communities with more family or household-related conflicts.</h>

<h2>20. Are thefts higher in January or July, and do their monthly counts move together with assaults?</h2>

In [35]:
jan_theft = df[(df['Primary Type']=="THEFT") & (df['Month']==1)]
jul_theft = df[(df['Primary Type']=="THEFT") & (df['Month']==7)]

theft_month = df[df['Primary Type']=="THEFT"].groupby('Month').size()
assault_month = df[df['Primary Type']=="ASSAULT"].groupby('Month').size()

print("January thefts:", len(jan_theft))
print("July thefts:", len(jul_theft))
print("Correlation theft vs assault:", theft_month.corr(assault_month))

January thefts: 4279
July thefts: 6053
Correlation theft vs assault: 0.8386293347453229

<h> Insight: July has more thefts, and thefts and assaults rise together by month.</h>

<h2>21. Are certain FBI codes linked with domestic crimes more than others?</h2>

fbi_domestic = (
    df.groupby("FBI Code")["Domestic"]
    .mean()
    .reset_index()
    .rename(columns={"Domestic": "Domestic_Rate"})
    .sort_values("Domestic_Rate", ascending=False)
)
fbi_domestic.head(10)

<h>Insight: The output reveals which FBI-defined crime categories (like assaults or sex offenses) are more likely to be classified as domestic in nature.</h>

<h2>22. How do arrest rates differ between crimes that happen indoors vs outdoors?</h2>

In [36]:
df["Indoor/Outdoor"] = df["Location Description"].apply(
    lambda x: "Indoor" if "RESIDENCE" in str(x).upper() or "APARTMENT" in str(x).upper() else "Outdoor"
)

indoor_outdoor = (
    df.groupby("Indoor/Outdoor")["Arrest"]
    .mean()
    .reset_index()
    .rename(columns={"Arrest": "Arrest_Rate"})
)
indoor_outdoor

  Indoor/Outdoor  Arrest_Rate
0         Indoor     0.091729
1        Outdoor     0.172443

<h>Insight: The results compare arrest likelihood in places like residences or buildings (indoors) versus streets or alleys (outdoors), showing where police action is stronger.</h>

<h2>23. Do certain districts have higher arrest rates for violent crimes compared to non-violent crimes?</h2>

In [37]:
violent_types = ["ASSAULT", "BATTERY", "HOMICIDE", "ROBBERY"]

df["Crime_Category"] = df["Primary Type"].apply(
    lambda x: "Violent" if x in violent_types else "Non-Violent"
)

district_violence = (
    df.groupby(["District", "Crime_Category"])["Arrest"]
    .mean()
    .reset_index()
    .rename(columns={"Arrest": "Arrest_Rate"})
    .sort_values("Arrest_Rate", ascending=False)
)
district_violence.head(10)

    District Crime_Category  Arrest_Rate
20        11    Non-Violent     0.373789
18        10    Non-Violent     0.250757
44        31    Non-Violent     0.230769
26        15    Non-Violent     0.210213
12         7    Non-Violent     0.209429
1          1        Violent     0.195930
41        24        Violent     0.181284
33        18        Violent     0.180077
0          1    Non-Violent     0.177746
37        20        Violent     0.174000

<h>Insight: The table highlights if police enforcement is stronger for violent incidents (like assault or homicide) than for non-violent offenses in each district.</h>

<h2>24. Which primary crime types happen most often in areas near certain latitude/longitude ranges?</h2>

In [38]:
df["Lat_Zone"] = pd.qcut(df["Latitude"], 3, labels=["South", "Central", "North"])

crime_by_zone = (
    df.groupby(["Lat_Zone", "Primary Type"])
    .size()
    .reset_index(name="Crime_Count")
    .sort_values("Crime_Count", ascending=False)
)
crime_by_zone.head(10)

   Lat_Zone     Primary Type  Crime_Count
91    North            THEFT        25275
60  Central            THEFT        19839
2     South          BATTERY        16565
33  Central          BATTERY        15019
29    South            THEFT        14059
64    North          BATTERY        12989
5     South  CRIMINAL DAMAGE        10503
1     South          ASSAULT         9167
36  Central  CRIMINAL DAMAGE         8521
67    North  CRIMINAL DAMAGE         8065

<h>Insight: This gives a geographical perspective, showing which crime types cluster in certain regions of the city (north, south, or central areas).</h>

<h2>25. Which combinations of year, primary type, and location description have the lowest arrest rates?</h2>

In [39]:
low_arrest_patterns = (
    df.groupby(["Year", "Primary Type", "Location Description"])["Arrest"]
    .mean()
    .reset_index()
    .rename(columns={"Arrest": "Arrest_Rate"})
    .sort_values("Arrest_Rate", ascending=True)
)
low_arrest_patterns.head(10)

      Year Primary Type         Location Description  Arrest_Rate
0     2024        ARSON           ABANDONED BUILDING          0.0
1163  2024  SEX OFFENSE           GROCERY FOOD STORE          0.0
32    2024        ARSON       SPORTS ARENA / STADIUM          0.0
1161  2024  SEX OFFENSE                  GAS STATION          0.0
29    2024        ARSON      SCHOOL - PUBLIC GROUNDS          0.0
28    2024        ARSON     SCHOOL - PUBLIC BUILDING          0.0
1158  2024  SEX OFFENSE              DAY CARE CENTER          0.0
25    2024        ARSON  RESIDENCE - PORCH / HALLWAY          0.0
1157  2024  SEX OFFENSE                    CTA TRAIN          0.0
1155  2024  SEX OFFENSE                 CTA PLATFORM          0.0

<h>Insight: The result highlights situations where crimes are frequent but rarely result in arrests, showing weak enforcement zones.</h>

<h2>26. What times of the year (months) have the highest crime counts, and which types dominate those months?</h2>

In [40]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
df["Month"] = df["Date"].dt.month

crime_by_month = (
    df.groupby(["Month", "Primary Type"])
    .size()
    .reset_index(name="Crime_Count")
    .sort_values("Crime_Count", ascending=False)
)
crime_by_month.head(10)

     Month Primary Type  Crime_Count
198      7        THEFT         6053
228      8        THEFT         5706
287     10        THEFT         5485
168      6        THEFT         5482
259      9        THEFT         5379
140      5        THEFT         5194
315     11        THEFT         4668
344     12        THEFT         4664
115      5      BATTERY         4447
83       3        THEFT         4391

<h>Insight: The results show seasonal patterns in crime — for example, whether theft spikes in summer months or assaults peak in winter.</h>

<h2>27. Which community areas have the lowest arrest rates despite having high crime counts?</h2>

In [41]:
community_low_arrests = (
    df.groupby("Community Area")["Arrest"]
    .agg(["count", "mean"])
    .reset_index()
    .rename(columns={"count": "Total_Crimes", "mean": "Arrest_Rate"})
    .sort_values(["Total_Crimes", "Arrest_Rate"], ascending=[False, True])
)
community_low_arrests.head(10)

    Community Area  Total_Crimes  Arrest_Rate
24            25.0         12814     0.196036
7              8.0         11019     0.150558
27            28.0         10489     0.108876
31            32.0          8975     0.205125
42            43.0          8190     0.115018
23            24.0          7615     0.076691
22            23.0          6936     0.300606
28            29.0          6605     0.238910
5              6.0          6585     0.089446
70            71.0          6365     0.131658

<h> Insight: The output identifies areas where many crimes happen but few lead to arrests, showing potential enforcement gaps.</h>

<h2> 28. Which locations report the most violent crimes, and what percentage of them are domestic?</h2>

In [42]:
violent_types = ["ASSAULT", "BATTERY", "HOMICIDE", "ROBBERY"]

violent_domestic = (
    df[df["Primary Type"].isin(violent_types)]
    .groupby("Location Description")[["Domestic"]]
    .mean()
    .reset_index()
    .rename(columns={"Domestic": "Domestic_Rate"})
    .sort_values("Domestic_Rate", ascending=False)
)
violent_domestic.head(10)

                      Location Description  Domestic_Rate
46                        CTA "L" PLATFORM       1.000000
94                               RESIDENCE       0.762567
15                               APARTMENT       0.738473
62                            FIRE STATION       0.666667
32                           CHA APARTMENT       0.608924
118                 VEHICLE NON-COMMERCIAL       0.583045
69                    HIGHWAY / EXPRESSWAY       0.529412
42   COLLEGE / UNIVERSITY - RESIDENCE HALL       0.500000
31                                CEMETARY       0.400000
63                         FOREST PRESERVE       0.375000

<h>Insight: The result highlights places (like streets, apartments, bars) where violent crimes are frequent, and shows how often they are connected to domestic situations.</h>

<h2>29. Which districts have the most domestic-related violent crimes, and how often do they end in arrests?</h2>

In [43]:
domestic_violent = (
    df[(df["Domestic"]) & (df["Primary Type"].isin(["ASSAULT", "BATTERY", "HOMICIDE"]))]
    .groupby("District")["Arrest"]
    .agg(["count", "mean"])
    .reset_index()
    .rename(columns={"count": "Domestic_Violent_Crimes", "mean": "Arrest_Rate"})
    .sort_values("Domestic_Violent_Crimes", ascending=False)
)
domestic_violent.head(10)

    District  Domestic_Violent_Crimes  Arrest_Rate
5          6                     2493     0.133975
3          4                     2233     0.166144
2          3                     2181     0.188904
7          8                     2177     0.194763
10        11                     1951     0.153767
6          7                     1916     0.157620
21        25                     1724     0.220998
13        15                     1678     0.176996
4          5                     1658     0.181544
1          2                     1599     0.153221

<h>Insight: The result identifies districts where domestic violence and violent crimes (like assault, homicide) overlap the most, and whether arrests are common.</h>

<h2>30. Which community areas have the most non-domestic crimes at public places (like streets and parks)?</h2>

In [44]:
public_non_domestic = (
    df[(df["Domestic"] == False) & 
       (df["Location Description"].str.contains("STREET|PARK", na=False))]
    .groupby("Community Area")["Primary Type"]
    .count()
    .reset_index(name="Public_NonDomestic_Crimes")
    .sort_values("Public_NonDomestic_Crimes", ascending=False)
)
public_non_domestic.head(10)

    Community Area  Public_NonDomestic_Crimes
27            28.0                       3422
24            25.0                       3392
23            24.0                       2779
7              8.0                       2593
31            32.0                       2301
22            23.0                       2217
42            43.0                       1953
28            29.0                       1859
70            71.0                       1761
68            69.0                       1695

<h>Insight: The findings show where public spaces face the most non-domestic crime activity, giving an idea of community safety in outdoor areas.</h>

<H1>Using District Area to make a comparison to a general result</H1>

In [45]:
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go

<h3>1. Crime Counts by Beat and Month</h3>

In [46]:
import pandas as pd
import plotly.express as px
import plotly.io as pio

crime_beat_month = (
    df.groupby(["Beat", "Month"])
    .size()
    .reset_index(name="Crime_Count")
    .pivot(index="Beat", columns="Month", values="Crime_Count")
    .fillna(0)
)

fig = px.imshow(
    crime_beat_month,
    color_continuous_scale="YlOrBr",
    labels=dict(x="Month", y="Beat", color="Crime Count"),
    title="Heatmap of Crime Counts by Beat and Month"
)

fig.show()  # 👈 Display in Jupyter
fig.write_html("heatmap_crime_by_beat_month.html")

<h>Insight: This shows crime seasonality at the neighborhood beat level. Some beats may have strong seasonal spikes (e.g., summer crimes), while others remain steady throughout the year.</h>

<h3>2. Crime Description vs Primary Type</h3>

In [84]:
import pandas as pd
import plotly.express as px
import plotly.io as pio

crime_desc_type = (
    df.groupby(["Primary Type", "Description"])
    .size()
    .reset_index(name="Count")
    .pivot(index="Primary Type", columns="Description", values="Count")
    .fillna(0)
)

fig = px.imshow(
    crime_desc_type,
    color_continuous_scale="Blues",  # pinalitan ng ibang kulay
    labels=dict(x="Description", y="Primary Type", color="Count"),
    title="Heatmap of Crime Descriptions by Primary Type"
)

# Styling malinis at malaki
fig.update_layout(
    width=1300,   # lapad ng figure
    height=800,   # taas ng figure
    font=dict(size=14, family="Times New Roman"),
    title=dict(font=dict(size=20)),
    xaxis=dict(
        tickangle=-90,   # nakatagilid labels para readable
        automargin=True,
        tickfont=dict(size=12)
    ),
    yaxis=dict(
        automargin=True,
        tickfont=dict(size=12)
    ),
    coloraxis_colorbar=dict(
        title=dict(
            text="Count",
            font=dict(size=16, family="Times New Roman")
        ),
        tickfont=dict(size=12)
    )
)



fig.update_traces(
    xgap=2, ygap=2
)

fig.show()
fig.write_html("heatmap_crime_desc_vs_type.html")

<h>Insight: This heatmap shows the detailed breakdown of what sub-crimes are driving each primary type. For example, theft might mostly be “retail theft,” while assault could be dominated by “simple assault.”</h>

<h3>3. Top Crime Type per District (Dominance Heatmap)</h3>

In [60]:
import pandas as pd
import plotly.express as px
import plotly.io as pio

top_type_district = (
    df.groupby(["District", "Primary Type"])
    .size()
    .reset_index(name="Count")
    .sort_values(["District", "Count"], ascending=[True, False])
    .groupby("District")
    .head(1)
    .set_index("District")[["Primary Type"]]
)

one_hot = pd.get_dummies(top_type_district["Primary Type"])

fig = px.imshow(
    crime_beat_month,
    color_continuous_scale=[[0, "blue"], [1, "red"]],  
    labels=dict(x="Month", y="Beat", color="Crime Count"),
    title="Heatmap of Crime Counts by Beat and Month"
)

fig.show()
fig.write_html("heatmap_top_crime_type_per_district.html")

<h> Insight: This highlights which single crime type dominates each district. For example, District A might be dominated by theft, while District B is dominated by narcotics.</h>

<h3>4. Arrest Rate per District</h3>

In [61]:
import pandas as pd
import plotly.express as px
import plotly.io as pio

arrest_by_district = (
    df.groupby("District")["Arrest"]
    .mean()
    .reset_index(name="Arrest_Rate")
    .set_index("District")
)

fig = px.imshow(
    arrest_by_district,
    color_continuous_scale="Blues",
    labels=dict(x="Arrest Rate", y="District", color="Rate"),
    title="Arrest Rate by District",
    aspect="auto"
)

fig.show()
fig.write_html("heatmap_arrest_rate_by_district.html")

<h>Insight: This makes it easy to see which districts have stronger enforcement. Darker = higher arrest rates.</h>

<h3>5. Crime Growth Over Years per District</h3>

In [71]:
import pandas as pd
import plotly.express as px

arrest_by_district = (
    df.groupby("District")["Arrest"]
    .mean()
    .reset_index(name="Arrest_Rate")
    .set_index("District")
)

fig = px.imshow(
    arrest_by_district,
    color_continuous_scale="Magma",
    labels=dict(x="Metric", y="District", color="Arrest Rate"),
    title="<b>Arrest Rate by District</b>",
    width=700,
    height=900,
    aspect="auto"  
)

# Styling
fig.update_traces(
    xgap=2, ygap=2, 
    selector=dict(type='heatmap')
)
fig.update_layout(
    font=dict(size=14, family="Arial Black"),
    xaxis_title=None,
    yaxis_title="District",
    coloraxis_colorbar=dict(
        title=dict(
            text="Rate",
            font=dict(size=16, family="Arial Black") 
        ),
        tickfont=dict(size=14)
    )
)

<h>Insight: This lets you see whether a district is improving (lighter colors over the years) or worsening (darker colors)</h>